### ISSUE TITLE
Complete example

### ISSUE THREAD

**Issue by eadgbear** [andylokandy/nom-rule#3]
Is there any way that you could put the example into a separate module? I can't get either the example in the readme or the tests module to compile. 

```
error: proc macro panicked
  --> src/main.rs:71:9
   |
71 |           nom_rule::rule!($crate::match_text, $crate::match_token, $($tt)*)
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
76 |       let mut rule = rule!(
   |  ____________________-
77 | |         CREATE ~ TABLE ~ #ident ~ ^"(" ~ (#ident ~ #ident ~ ","?)* ~ ")" ~ ";" : "CREATE TABLE statement"
78 | |     );
   | |_____- in this macro invocation

   = help: message: called `Option::unwrap()` on a `None` value
   = note: this error originates in the macro `rule` (in Nightly builds, run with -Z macro-backtrace for more info)

```

Also is it possible to use rules inside of other rules?

**Comment by ilyatrefilov** [comment]
Issue seems to arise from the usage of [Span::join](https://docs.rs/proc-macro2/latest/proc_macro2/struct.Span.html#method.join) in this crate, which is available on nightly only. So i guess it should be mentioned in readme that this crate is for nightly compiler only until `proc_macro_span` feature is available on stable.

**Comment by andylokandy** [comment]
Yes! As @ilyatrefilov said, this crate is only available on the nightly channel for the exact reason. So I'll suggest you use the nightly compiler instead. I appreciate your feedback and I've added a note to the readme.

If you're interested in the usage in a real production project, it'll be helpful to read the SQL parser of the cloud-native database [databend](https://github.com/datafuselabs/databend/blob/cd08fb5f826ba318aef819f993d3773f6566a7e8/src/query/ast/src/parser/statement.rs).

**Comment by eadgbear** [comment]
Thanks!
